<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>44_await_函數</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <div class="container"></div>
  <script>
    async function main() {
      let p = new Promise((resolve, reject) => {
        // resolve("OK");
        reject("error");
      });
      // 1. 右側為 Promise 的情況，await 會返回 Promise 對象成功的值
      // let res = await p;
      // console.log(res); // OK
      
      // 2. 右側為其他類型的數據，右側是甚麼，await 就返回甚麼
      // let res2 = await "Hello";
      // console.log(res2); // Hello

      // 3. 如果右側 Promise 是失敗的狀態
      try{
        let res3 = await p
      } catch(e) {
        console.log(e);
      }
    }

    main();
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>